#!/usr/bin/bash

displays=$(xrandr -q | grep ' connected' | sed 's/^\([^ ]*\) .*$/\1/')
YES=yes
if [[ $1 == dec ]] ; then
	DECREASE=$YES
fi
if [[ $DECREASE == $YES ]] ; then
	OP='-'
else
	OP='+'
fi
STEP=0.1
MAX=2.0
MIN=0.1

# Loop on all displays
for display in $displays ; do

	# Get current brightness
	brightness=$(xrandr --verbose | grep -i brightness | head -n 1 | sed 's/.*[Bb]rightness: *\([0-9.]*\)$/\1/')

	# Compute new brightness
	brightness=$(echo "$brightness $OP $STEP" | bc -l)
	if [[ $(echo "$brightness > $MAX" | bc -l) -eq 1 ]] ; then
		brightness=$MAX
	fi
	if [[ $(echo "$brightness < $MIN" | bc -l) -eq 1 ]] ; then
		brightness=$MIN
	fi

	# Set new brightness
	xrandr --output $display --brightness $brightness
done
