#!/bin/bash
# vi: ft=sh fdm=marker

# Constants {{{1
################################################################

# uname
UNAME=$(which uname)
if [ -z "$UNAME" ] ; then
	echo "Cannot find uname program." >&2
	exit 1
fi

# OS type
PLATFORM=
if [ -n "$UNAME" ] ; then
	PLATFORM=$($UNAME)
fi

# Main {{{1
################################################################

if [[ $PLATFORM == Darwin ]] ; then
	charge=$(pmset -g batt | grep InternalBattery | sed -E 's/^.*[[:space:]]([[:digit:]]+%).*$/\1/')
	plugged=$(pmset -g batt | grep InternalBattery | sed -E -e 's/^.*InternalBattery[^;]*; *([^;]*) *;.*$/\1/' -e 's/discharging/v/' -e 's/charging|AC attached/^/' -e 's/charged//')
elif [[ $PLATFORM == Linux ]] && which acpi >/dev/null 2>/dev/null ; then
	charge=$(acpi -b | sed 's/^.* \([0-9]\+%\).*$/\1/')
	plugged=$(acpi -a | sed -e 's/^.* \(on\|off\)-line$/\1/' -e 's/on/^/' -e 's/off/v/')
fi
echo "$charge$plugged"
