#!/usr/bin/bash

# Get card name
wifi_card=$(iw dev | grep Interface)
# or
lspci | egrep -i 'wifi|broadcon|wlan|wireless'

# Get card information
lspci -vv -s 02:00.0 # card index 02:00.0 get from previous call

# Get SSID
wifi_ssid=$(iw dev | grep ssid)

# Get info
iw $wifi_card info

# Get IP
wifi_ip=$(ifconfig $card)

# Link quality
cat /proc/net/wireless
