#!/usr/bin/bash

# Choose terminal
for term in $TERMINAL urxvt xfce4-terminal xterm ; do
	term_exists=$(which $term 2>/dev/null)
	if [[ -n $term_exists ]] ; then
		TERMINAL=$term
		break
	fi
done

X_PROGS=,openmw,
TERM_PROGS=,vim,R,ranger,htop,

debug() {
	local m=$1

	echo DEBUG $m >&2
}

is_xprg() {
	local ret=1
	local prg=
	
	for prg in $* ; do

		# Search in NO X personal list
		is_not_xprg=$(echo $TERM_PROGS | grep ",$prg,")
		debug "is_not_xprg=$is_not_xprg"
		[[ -n $is_not_xprg ]] && break

		# Search in .desktop files
		local is_xprg=$(cat /usr/share/applications/*.desktop | grep ^Exec= | sed 's/^Exec=\([^ ]*\).*/\1/' | sed 's!^.*/\([^/]*\)$!\1!' | sort | uniq | grep "^$prg$")
		debug "is_xprg=$is_xprg"

		# Search in X personal list
		if [[ -z $is_xprg ]] ; then
			is_xprg=$(echo $X_PROGS | grep ",$prg,")
		fi
		debug "is_xprg=$is_xprg"

		# Return if is an X prog
		if [[ -n $is_xprg ]] ; then
			ret=0
			break
		fi
	done
	debug "ret=$ret"

	return $ret
}

# Get font
font=$(xrdb -query -all | grep font | head -n 1 | sed 's/^.*: *//')
[[ -n $font ]] || font=6x13

# Get choice
prg=$(dmenu_path | dmenu -fn "$font" -i -b -p '>' -nb '#000077' -nf '#bbbb00' -sb '#777700' -sf '#0000bb')
debug "prg=$prg"

# Get real prog if sym link
prg_path=$(which $prg)
debug "prg_path=$prg_path"
if [[ -L $prg_path ]] ; then
	realprg=$(readlink $prg_path)
fi
debug "realprg=$realprg"

# Execute
if is_xprg $prg $realprg ; then
	debug "Run as X prog"
	$prg
else
	debug "Run as term prog"
	title=$(basename $(echo "$prg" | sed 's/ .*$//'))
	$TERMINAL -T "$title" -e "$prg"
fi
